### ISSUE TITLE
Saving model behavior to database

### ISSUE THREAD

**Issue by ardila** [dicarlolab/BehavioralBenchmark#14]
Save raw, format for consistency metric, and list of neurons subsampled for now.

**Comment by ardila** [comment]
Had to stop here for today. @yamins81, or @toosi does this error ring any bells for you? I passed in what I thought were pretty standard arguments for compute_metric_base and I got this

```
Traceback (most recent call last):
  File "/mindhive/dicarlolab/u/ardila/virtual_environments/default/src/BehavioralBenchmark/BehavioralBenchmark/ImageLevel/test_store_feature_results.py", line 32, in test_store_subsampled_features
    self.additional_info)
  File "/mindhive/dicarlolab/u/ardila/virtual_environments/default/src/BehavioralBenchmark/BehavioralBenchmark/ImageLevel/store_feature_results.py", line 82, in store_subsampled_feature_results
    store_compute_metric_results(F, meta, eval_config, fs, additional_info)
  File "/mindhive/dicarlolab/u/ardila/virtual_environments/default/src/BehavioralBenchmark/BehavioralBenchmark/ImageLevel/store_feature_results.py", line 62, in store_compute_metric_results
    results = compute_metric_base(F, meta, eval_config)
  File "/mindhive/dicarlolab/u/ardila/virtual_environments/default/src/dldata/dldata/metrics/utils.py", line 1661, in compute_metric_base
    compute_classifier_metrics(result, split_results, metric_kwargs, objinds, res_labelset, metric_lbls)
  File "/mindhive/dicarlolab/u/ardila/virtual_environments/default/src/dldata/dldata/metrics/utils.py", line 1726, in compute_classifier_metrics
    cms.append(split_result['test_cm'])
KeyError: 'test_cm'
```

**Comment by yamins81** [comment]
@ardila ...   Possibly a bug introduced by other commits I've made.   Can I sit down with you and look at the specific spec and see if I can debug it with you?
